project_id = "xsmjjkbycrzberloywqm"

[functions.send-inquiry]
verify_jwt = false

[functions.delete-user]
verify_jwt = false

[functions.share-biler]
verify_jwt = false

[functions.og-bil]
verify_jwt = false

[functions.generate-invite-link]
verify_jwt = false